# Generated by Django 5.2.17 on 2026-10-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='finance_acc_owner__f1c2e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='finance_cat_owner__a4b7d1_idx',
        ),
        migrations.RenameIndex(
            model_name='budget',
            new_name='finance_bud_owner_i_06b797_idx',
            old_name='finance_bud_owner__8c5e21_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finance_tra_owner_i_c6a1ca_idx',
            old_name='finance_tra_owner__d6e9f2_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finance_tra_account_e5c58b_idx',
            old_name='finance_tra_account_7f3a10_idx',
        ),
    ]
